[package]
name = "clipr"
version = "0.1.2"
edition = "2021"

[dependencies]
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
pareg = "0.10.0"
termal = { version = "4.1.0", features = ["events"]}
thiserror = "2.0.17"
